version: 2 

sources:
  - name: dummy_source
    description: table representation of the seed data, not real
    schema: "{{ target.schema }}"
    database: "{{ target.database }}"
    tables:
      - name: sapling